---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(tseries)
library(forecast)
data = read.csv("BTC.csv",header=T)
data$CSSD = sqrt((data$Market_Return - data$BTC_Return)^2 + (data$Market_Return - data$LTC_Return)^2)
model = lm(CSSD ~ Upper + Lower,data=data)
summary(model)
```


```{r}
data$Market_Return_2 = (data$Market_Return)^2
data$Market_Return_abs = abs(data$Market_Return)
data$CASD = (abs(data$Market_Return - data$BTC_Return) + abs(data$Market_Return - data$LTC_Return))/2
head(data)
```

```{r}
model = lm(CASD ~ Market_Return + Market_Return_abs + Market_Return_2,data=data)
summary(model)
```

```{r}
data$beta_1 = data$Market_Return * data$D
data$beta_2 = data$Market_Return * data$D_1
data$beta_3 = data$Market_Return_2 * data$D
data$beta_4 = data$Market_Return_2 * data$D_1
```

```{r}
model = lm(CASD ~ beta_1 + beta_2 + beta_3 + beta_4,data=data)
summary(model)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```