---
title: "TS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(tseries)
library(forecast)
BTC = read.csv("BTC.csv",header=T)
ETH = read.csv("ETH.csv",header=T)
LTC = read.csv("LTC.csv",header=T)
XRP = read.csv("XRP.csv",header=T)

LTC = arrange(LTC, -row_number())
XRP = arrange(XRP, -row_number())

BTC$Date = as.character(BTC$Date)
BTC$Date = as.Date(str_sub(BTC$Date,1,9))

ETH$Date = as.character(ETH$Date)
ETH$Date = as.Date(str_sub(ETH$Date,1,9))

Sys.setlocale("LC_TIME", "C")
LTC$Date = as.character(LTC$Date)
LTC$Date = as.Date(LTC$Date, "%b %d, %Y")
XRP$Date = as.character(XRP$Date)
XRP$Date = as.Date(XRP$Date, "%b %d, %Y")
```

```{r}
# Plot
par(mfrow=c(2,2))
plot(BTC$Date,BTC$Close,type="l",main="BitCoin")
plot(ETH$Date,ETH$Close,type="l",main="Ethereum ")
plot(LTC$Date,LTC$Close,type="l",main="LiteCoin")
plot(XRP$Date,XRP$Close,type="l",main="XRP")
```

```{r}
adf.test(BTC$Close)
adf.test(ETH$Close)
adf.test(LTC$Close)
adf.test(XRP$Close)
```

```{r}
data = LTC
#data = data[(unique(data$Date)),]
size = dim(data)[1]
data$Return = 1:size
for (i in 2:size)
{
  data$Return[i] = data$Close[i]/data$Close[i-1] - 1
}
data = data[2:size,]
#fit = arima(data$Return, order = c(2,0, 2))
fit = auto.arima(data$Return, stationary=TRUE)
summary(fit)
checkresiduals(fit)

# Forecasted Fit
 data_train <-data$Return[1:(0.9 * length(data$Return))]  # Train dataset
 data_test <- data$Return[(0.9 * length(data$Return) + 1):length(data$Return)]  # Test dataset

 fit <- arima(data_train, order = c(2, 0, 2))
 arma.preds <- predict(fit, n.ahead = (length(data$Return) - (0.9 * length(data$Return))))$pred
 arma.forecast <- forecast(fit,h=25)

plot(arma.forecast, main = "ARIMA forecasts for XRP returns")
# adf.test(data$Return)
```

```{r}
library(rugarch)
library(rmgarch)
# library(tseries)
# library(xts)

data = LTC
#data = data[(unique(data$Date)),]
size = dim(data)[1]
data$Return = 1:size
for (i in 2:size)
{
  data$Return[i] = data$Close[i]/data$Close[i-1] - 1
}
data = data[2:size,]

ug_spec = ugarchspec(mean.model=list(armaOrder=c(1,1)))
fit = ugarchfit(spec = ug_spec, data = data$Return)
#fit = garch(data$Return,order=c(1,1))
#summary(fit)
#fit@fit$coef
fit

# Forecasted Fit
# data_train <-data$Return[1:(0.9 * length(data$Return))]  # Train dataset
# data_test <- data$Return[(0.9 * length(data$Return) + 1):length(data$Return)]  # Test dataset

# fit <- arima(data_train, order = c(2, 0, 2))
# arma.preds <- predict(fit, n.ahead = (length(data$Return) - (0.9 * length(data$Return))))$pred
# arma.forecast <- forecast(fit,h=25)

# plot(arma.forecast, main = "ARMA forecasts for XRP returns")
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```